// CREATE
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

// LIST
export const BEGIN_DOWNLOAD_POST = 'BEGIN_DOWNLOAD_POST';
export const DOWNLOAD_POST_SUCCESS = 'DOWNLOAD_POST_SUCCESS';
export const DOWNLOAD_POST_ERROR = 'DOWNLOAD_POST_SUCCESS';