// CREATE
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

// LIST
export const BEGIN_DOWNLOAD_POST = 'BEGIN_DOWNLOAD_POST';
export const DOWNLOAD_POST_SUCCESS = 'DOWNLOAD_POST_SUCCESS';
export const DOWNLOAD_POST_ERROR = 'DOWNLOAD_POST_ERROR';

// DELETE
export const GIVE_POST_DELETE = 'GIVE_POST_DELETE';
export const POST_DELETED_SUCCESS = 'POST_DELETED_SUCCESS';
export const POST_DELETED_ERROR = 'POST_DELETED_ERROR';


// EDIT
export const GIVE_POST_EDIT = 'GIVE_POST_EDIT';
export const BEGIN_EDIT_POST = 'BEGIN_EDIT_POST';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_ERROR = 'POST_EDIT_ERROR';