export const postTypes = {
    
    ADD_POST : 'ADD_POST',
    ADD_POST_SUCCESS : 'ADD_POST_SUCCESS',
    ADD_POST_ERROR : 'ADD_POST_ERROR',

    
    BEGIN_DOWNLOAD_POST : 'BEGIN_DOWNLOAD_POST',
    DOWNLOAD_POST_SUCCESS : 'DOWNLOAD_POST_SUCCESS',
    DOWNLOAD_POST_ERROR : 'DOWNLOAD_POST_ERROR',

    
    GIVE_POST_DELETE : 'GIVE_POST_DELETE',
    POST_DELETED_SUCCESS : 'POST_DELETED_SUCCESS',
    POST_DELETED_ERROR : 'POST_DELETED_ERROR',

    
    GIVE_POST_EDIT : 'GIVE_POST_EDIT',
    BEGIN_EDIT_POST : 'BEGIN_EDIT_POST',
    POST_EDIT_SUCCESS : 'POST_EDIT_SUCCESS',
    POST_EDIT_ERROR : 'POST_EDIT_ERROR',  
}